version: "3"
services:
  app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/usr/src/app
    ports:
      - "3000:3000"
    command: npx nodemon --exec npx ts-node src/index.ts
